import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <form
        dir="rtl"
        id="donation-form"
        action="/api/create-subscription"
        method="post"
        className="rounded-lg bg-white p-6"
      >
        <h2 className="mb-4 text-lg font-medium">טופס תרומה</h2>
      
        <div className="mb-4">
          <label className="mb-2 block font-medium text-gray-700">
            שם מלא <span className="text-red-700">*</span>
          </label>
          <input
            required
            className="w-full rounded-lg border border-gray-400 p-2"
            type="text"
            name="full_name"
          />
        </div>

        <div className="mb-4">
          <label className="mb-2 block font-medium text-gray-700">
            דואר אלקטרוני
          </label>
          <input
            className="w-full rounded-lg border border-gray-400 p-2"
            type="email"
            name="email"
            placeholder="כתוב את כתובת הדואר האלקטרוני שלך"
          />
        </div>

        <div className="mb-4">
          <label className="mb-2 block font-medium text-gray-700">
            טלפון נייד
          </label>
          <input
            className="w-full rounded-lg border border-gray-400 p-2"
            type="tel"
            name="phone"
            placeholder="כתוב את מספר הטלפון הנייד שלך"
          />
        </div>

        <div className="mb-4 flex justify-start">
          <input
            className=" rounded-lg border border-gray-400"
            type="checkbox"
            name="anonymous"
          />
          <label className="mx-2 block font-medium text-gray-700">
            תרומה אנונימית
          </label>
        </div>

        <div className="mb-4">
          <label className="mb-2 block font-medium text-gray-700">הקדשה</label>
          <textarea
            className="h-36 w-full rounded-lg border border-gray-400 p-2"
            name="dedication"
          />
        </div>
      </form>
    </>
  );
};

export default Home;
